spring.application.name=demo
logging.level.org.mongodb.driver=DEBUG
spring.data.mongodb.uri=mongodb+srv://teodoram555_db_user:XliMRIEb1yKHyZXn@dev-cluster.armwukf.mongodb.net/demo
spring.mongodb.uri=mongodb+srv://teodoram555_db_user:XliMRIEb1yKHyZXn@dev-cluster.armwukf.mongodb.net/demo
spring.data.mongodb.auto-index-creation=true    
